import { Extension, textInputRule } from '@tiptap/core';

const customTextInputRules = Extension.create({
  name: 'customTextInputRules',

  addInputRules() {
    return [
      textInputRule({
        find: /1st\s$/,
        replace: '1ˢᵗ ',
      }),
      textInputRule({
        find: /2nd\s$/,
        replace: '2ⁿᵈ ',
      }),
      textInputRule({
        find: /3rd\s$/,
        replace: '3ʳᵈ ',
      }),
      textInputRule({
        find: /4th\s$/,
        replace: '4ᵗʰ ',
      }),
      textInputRule({
        find: /5th\s$/,
        replace: '5ᵗʰ ',
      }),
      textInputRule({
        find: /6th\s$/,
        replace: '6ᵗʰ ',
      }),
      textInputRule({
        find: /7th\s$/,
        replace: '7ᵗʰ ',
      }),
      textInputRule({
        find: /8th\s$/,
        replace: '8ᵗʰ ',
      }),
      textInputRule({
        find: /9th\s$/,
        replace: '9ᵗʰ ',
      }),
      textInputRule({
        find: /10th\s$/,
        replace: '10ᵗʰ ',
      }),
      textInputRule({
        find: /11th\s$/,
        replace: '11ᵗʰ ',
      }),
      textInputRule({
        find: /12th\s$/,
        replace: '12ᵗʰ ',
      }),
      textInputRule({
        find: /13th\s$/,
        replace: '13ᵗʰ ',
      }),
      textInputRule({
        find: /14th\s$/,
        replace: '14ᵗʰ ',
      }),
      textInputRule({
        find: /15th\s$/,
        replace: '15ᵗʰ ',
      }),
      textInputRule({
        find: /16th\s$/,
        replace: '16ᵗʰ ',
      }),
      textInputRule({
        find: /17th\s$/,
        replace: '17ᵗʰ ',
      }),
      textInputRule({
        find: /18th\s$/,
        replace: '18ᵗʰ ',
      }),
      textInputRule({
        find: /19th\s$/,
        replace: '19ᵗʰ ',
      }),
      textInputRule({
        find: /20th\s$/,
        replace: '20ᵗʰ ',
      }),
      textInputRule({
        find: /21st\s$/,
        replace: '21ˢᵗ ',
      }),
      textInputRule({
        find: /22nd\s$/,
        replace: '22ⁿᵈ ',
      }),
      textInputRule({
        find: /23rd\s$/,
        replace: '23ʳᵈ ',
      }),
      textInputRule({
        find: /24th\s$/,
        replace: '24ᵗʰ ',
      }),
      textInputRule({
        find: /25th\s$/,
        replace: '25ᵗʰ ',
      }),
      textInputRule({
        find: /26th\s$/,
        replace: '26ᵗʰ ',
      }),
      textInputRule({
        find: /27th\s$/,
        replace: '27ᵗʰ ',
      }),
      textInputRule({
        find: /28th\s$/,
        replace: '28ᵗʰ ',
      }),
      textInputRule({
        find: /29th\s$/,
        replace: '29ᵗʰ ',
      }),
      textInputRule({
        find: /30th\s$/,
        replace: '30ᵗʰ ',
      }),
      textInputRule({
        find: /31st\s$/,
        replace: '31ˢᵗ ',
      }),
      // textInputRule({ find: /-___- $/, replace: '😑 ' }),
      // textInputRule({ find: /:'-\) $/, replace: '😂 ' }),
      // textInputRule({ find: /':-\) $/, replace: '😅 ' }),
      // textInputRule({ find: /':-D $/, replace: '😅 ' }),
      // textInputRule({ find: />:-\) $/, replace: '😆 ' }),
      // textInputRule({ find: /-__- $/, replace: '😑 ' }),
      // textInputRule({ find: /':-\( $/, replace: '😓 ' }),
      // textInputRule({ find: /:'-\( $/, replace: '😢 ' }),
      // textInputRule({ find: />:-\( $/, replace: '😠 ' }),
      // textInputRule({ find: /O:-\) $/, replace: '😇 ' }),
      // textInputRule({ find: /0:-3 $/, replace: '😇 ' }),
      // textInputRule({ find: /0:-\) $/, replace: '😇 ' }),
      // textInputRule({ find: /0;\^\) $/, replace: '😇 ' }),
      // textInputRule({ find: /O;-\) $/, replace: '😇 ' }),
      // textInputRule({ find: /0;-\) $/, replace: '😇 ' }),
      // textInputRule({ find: /O:-3 $/, replace: '😇 ' }),
      // textInputRule({ find: /:'\) $/, replace: '😂 ' }),
      // textInputRule({ find: /:-D $/, replace: '😃 ' }),
      // textInputRule({ find: /':\) $/, replace: '😅 ' }),
      // textInputRule({ find: /'=\) $/, replace: '😅 ' }),
      // textInputRule({ find: /':D $/, replace: '😅 ' }),
      // textInputRule({ find: /'=D $/, replace: '😅 ' }),
      // textInputRule({ find: />:\) $/, replace: '😆 ' }),
      // textInputRule({ find: />;\) $/, replace: '😆 ' }),
      // textInputRule({ find: />=\) $/, replace: '😆 ' }),
      // textInputRule({ find: /;-\) $/, replace: '😉 ' }),
      // textInputRule({ find: /\*-\) $/, replace: '😉 ' }),
      // textInputRule({ find: /;-\] $/, replace: '😉 ' }),
      // textInputRule({ find: /;\^\) $/, replace: '😉 ' }),
      // textInputRule({ find: /B-\) $/, replace: '😎 ' }),
      // textInputRule({ find: /8-\) $/, replace: '😎 ' }),
      // textInputRule({ find: /B-D $/, replace: '😎 ' }),
      // textInputRule({ find: /8-D $/, replace: '😎 ' }),
      // textInputRule({ find: /:-\* $/, replace: '😘 ' }),
      // textInputRule({ find: /:\^\* $/, replace: '😘 ' }),
      // textInputRule({ find: /:-\) $/, replace: '🙂 ' }),
      // textInputRule({ find: /-_- $/, replace: '😑 ' }),
      // textInputRule({ find: /:-X $/, replace: '😶 ' }),
      // textInputRule({ find: /:-# $/, replace: '😶 ' }),
      // textInputRule({ find: /:-x $/, replace: '😶 ' }),
      // textInputRule({ find: />.< $/, replace: '😣 ' }),
      // textInputRule({ find: /:-O $/, replace: '😮 ' }),
      // textInputRule({ find: /:-o $/, replace: '😮 ' }),
      // textInputRule({ find: /O_O $/, replace: '😮 ' }),
      // textInputRule({ find: />:O $/, replace: '😮 ' }),
      // textInputRule({ find: /:-P $/, replace: '😛 ' }),
      // textInputRule({ find: /:-p $/, replace: '😛 ' }),
      // textInputRule({ find: /:-Þ $/, replace: '😛 ' }),
      // textInputRule({ find: /:-þ $/, replace: '😛 ' }),
      // textInputRule({ find: /:-b $/, replace: '😛 ' }),
      // textInputRule({ find: />:P $/, replace: '😜 ' }),
      // textInputRule({ find: /X-P $/, replace: '😜 ' }),
      // textInputRule({ find: /x-p $/, replace: '😜 ' }),
      // textInputRule({ find: /':\( $/, replace: '😓 ' }),
      // textInputRule({ find: /'=\( $/, replace: '😓 ' }),
      // textInputRule({ find: />:\\ $/, replace: '😕 ' }),
      // textInputRule({ find: />:\/ $/, replace: '😕 ' }),
      // textInputRule({ find: /:-\/ $/, replace: '😕 ' }),
      // textInputRule({ find: /:-. $/, replace: '😕 ' }),
      // textInputRule({ find: />:\[ $/, replace: '😞 ' }),
      // textInputRule({ find: /:-\( $/, replace: '😞 ' }),
      // textInputRule({ find: /:-\[ $/, replace: '😞 ' }),
      // textInputRule({ find: /:'\( $/, replace: '😢 ' }),
      // textInputRule({ find: /;-\( $/, replace: '😢 ' }),
      // textInputRule({ find: /#-\) $/, replace: '😵 ' }),
      // textInputRule({ find: /%-\) $/, replace: '😵 ' }),
      // textInputRule({ find: /X-\) $/, replace: '😵 ' }),
      // textInputRule({ find: />:\( $/, replace: '😠 ' }),
      // textInputRule({ find: /0:3 $/, replace: '😇 ' }),
      // textInputRule({ find: /0:\) $/, replace: '😇 ' }),
      // textInputRule({ find: /O:\) $/, replace: '😇 ' }),
      // textInputRule({ find: /O=\) $/, replace: '😇 ' }),
      // textInputRule({ find: /O:3 $/, replace: '😇 ' }),
      // textInputRule({ find: /<\/3 $/, replace: '💔 ' }),
      // textInputRule({ find: /:D $/, replace: '😃 ' }),
      // textInputRule({ find: /=D $/, replace: '😃 ' }),
      // textInputRule({ find: /;\) $/, replace: '😉 ' }),
      // textInputRule({ find: /\*\) $/, replace: '😉 ' }),
      // textInputRule({ find: /;\] $/, replace: '😉 ' }),
      // textInputRule({ find: /;D $/, replace: '😉 ' }),
      // textInputRule({ find: /B\) $/, replace: '😎 ' }),
      // textInputRule({ find: /8\) $/, replace: '😎 ' }),
      // textInputRule({ find: /:\* $/, replace: '😘 ' }),
      // textInputRule({ find: /=\* $/, replace: '😘 ' }),
      // textInputRule({ find: /:\) $/, replace: '🙂 ' }),
      // textInputRule({ find: /=\] $/, replace: '🙂 ' }),
      // textInputRule({ find: /=\) $/, replace: '🙂 ' }),
      // textInputRule({ find: /:\] $/, replace: '🙂 ' }),
      // textInputRule({ find: /:X $/, replace: '😶 ' }),
      // textInputRule({ find: /:# $/, replace: '😶 ' }),
      // textInputRule({ find: /=X $/, replace: '😶 ' }),
      // textInputRule({ find: /=x $/, replace: '😶 ' }),
      // textInputRule({ find: /:x $/, replace: '😶 ' }),
      // textInputRule({ find: /=# $/, replace: '😶 ' }),
      // textInputRule({ find: /:O $/, replace: '😮 ' }),
      // textInputRule({ find: /:o $/, replace: '😮 ' }),
      // textInputRule({ find: /:P $/, replace: '😛 ' }),
      // textInputRule({ find: /=P $/, replace: '😛 ' }),
      // textInputRule({ find: /:p $/, replace: '😛  ' }),
      // textInputRule({ find: /=p $/, replace: '😛 ' }),
      // textInputRule({ find: /:Þ $/, replace: '😛 ' }),
      // textInputRule({ find: /:þ $/, replace: '😛 ' }),
      // textInputRule({ find: /:b $/, replace: '😛 ' }),
      // textInputRule({ find: /d: $/, replace: '😛 ' }),
      // textInputRule({ find: /:\/ $/, replace: '😕 ' }),
      // textInputRule({ find: /:\\ $/, replace: '😕 ' }),
      // textInputRule({ find: /=\/ $/, replace: '😕 ' }),
      // textInputRule({ find: /=\\ $/, replace: '😕 ' }),
      // textInputRule({ find: /:L $/, replace: '😕 ' }),
      // textInputRule({ find: /=L $/, replace: '😕 ' }),
      // textInputRule({ find: /:\( $/, replace: '😞 ' }),
      // textInputRule({ find: /:\[ $/, replace: '😞 ' }),
      // textInputRule({ find: /=\( $/, replace: '😞 ' }),
      // textInputRule({ find: /;\( $/, replace: '😢 ' }),
      // textInputRule({ find: /D: $/, replace: '😨 ' }),
      // textInputRule({ find: /:\$ $/, replace: '😳 ' }),
      // textInputRule({ find: /=\$ $/, replace: '😳 ' }),
      // textInputRule({ find: /#\) $/, replace: '😵 ' }),
      // textInputRule({ find: /%\) $/, replace: '😵 ' }),
      // textInputRule({ find: /X\) $/, replace: '😵 ' }),
      // textInputRule({ find: /:@ $/, replace: '😠 ' }),
      // textInputRule({ find: /<3 $/, replace: '❤️ ' }),
      // textInputRule({ find: /\/shrug $/, replace: '¯\\_(ツ)_/¯' }),
      // textInputRule({ find: /;\) $/, replace: '😉 ' }),
      // textInputRule({ find: /:\)\] $/, replace: '🙂 ' })
    ];
  },
});

export default customTextInputRules;
